name: Prettier Code Style

# Triggers the prettier workflow on push and pull request events
on: [push, pull_request]

jobs:
  Prettier:
    name: Prettier run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install npm dependencies
        run: npm install
      - name: Prettier Write
        run: npm run format
      - name: Prettier Format
        run: npm run lint